---
- name: "Ensure nginx container"
  docker_container:
    image: "{{ nginx_image }}"
    name: "{{ nginx_name }}"
    restart_policy: always
    state: start
    published_ports:
      - 80:8080
      - 443:8443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt:delegated
    env: "{{ nginx_environment }}"
