---
- name: "Ensure nginx container"
  docker_container:
    image: "{{ nginx_image }}"
    name: "{{ nginx_name }}"
    restart_policy: always
    state: started
    published_ports:
      - 80:8080
      - 443:8443
    volumes:
      - /root/fullchain.pem:/etc/ssl/fullchain.pem:delegated
      - /root/key.pem:/etc/ssl/key.pem:delegated
    env: "{{ nginx_environment }}"
