trigger:
  paths:
    include:
      - .dockerignore
      - azure-pipelines.yaml
      - pipeline-templates
      - src
      - common
  branches:
    include:
      - master
      - develop
      - feature/*

variables:
  sourceDirectory: "$(Build.SourcesDirectory)/src/frontend"

  repository: survivorbat/portfolio
  dockerServiceConnection: DockerHub
  azureServiceConnection: ARM
  terraformDirectory: $(Build.SourcesDirectory)/common/terraform
  tag: nginx-$(Build.SourceBranchName)-$(Build.BuildNumber)
  privateKeyName: azure_rsa

  node_version: "13.7.0"
  nginx_jinja_version: "1.17.9"

stages:
  - stage: Build_and_Test
    displayName: Build and test
    jobs:
      - job: Build
        displayName: Build and test
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(repository)
              arguments: --build-arg node_version=$(node_version) --build-arg nginx_jinja_version=$(nginx_jinja_version)
              tags: |
                $(tag)
                latest
      - job: TFValidate
        displayName: Validate Terraform Config
        steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in terraform/*.tf'
            inputs:
              targetFiles: 'terraform/**/*.tf'
              tokenPrefix: '__'
              tokenSuffix: '__'

          - template: pipeline-templates/terraform-validate.yaml@templates
            parameters:
              backendType: azurerm
              backendServiceArm: $(azureServiceConnection)
              environmentServiceName: $(azureServiceConnection)
              backendAzureRmStorageAccountName: $(storageAccountName)
              backendAzureRmResourceGroupName: AvansInfra
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: $(azureRmKey)
              terraformDirectory: $(terraformDirectory)

  - stage: Deploy
    displayName: Deploy
    condition: and(succeeded(), eq(variables['build.sourcebranchname'], 'master'))
    jobs:
      - job: Docker_Publish
        displayName: Publish Docker Image
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerServiceConnection)
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(repository)
              containerRegistry: $(dockerServiceConnection)
              arguments: --build-arg node_version=$(node_version) --build-arg nginx_jinja_version=$(nginx_jinja_version)
              tags: |
                $(tag)
                latest
          - task: Docker@2
            displayName: Publish
            inputs:
              command: push
              repository: $(repository)
              containerRegistry: $(dockerServiceConnection)
              tags: |
                $(tag)
                latest
      - job: Infra_Deploy
        displayName: Terraform Deploy
        dependsOn: Docker_Publish
        steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in terraform/*.tf'
            inputs:
              targetFiles: 'common/terraform/*.tf'
              tokenPrefix: '__'
              tokenSuffix: '__'

          - template: pipeline-templates/terraform-deploy.yaml
            parameters:
              backendType: azurerm
              backendServiceArm: $(azureServiceConnection)
              environmentServiceName: $(azureServiceConnection)
              backendAzureRmStorageAccountName: $(storageAccountName)
              backendAzureRmResourceGroupName: Portfolio
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: $(azureRmKey)
              terraformDirectory: $(terraformDirectory)

      - job: Infra_Configure
        displayName: Ansible
        dependsOn: Infra_Deploy
        steps:
          - template: pipeline-templates/ansible-deploy.yaml
            parameters:
              rootDirectory: "$(Build.SourcesDirectory)/common/ansible"
              inventoryFileName: "inventories/prod.yaml"
              ansibleEnvironment:
                doToken: $(doToken)
                letsencryptEmail: $(letsencryptEmail)
                personalPublicKey: $(personalPublicKey)
                portfolioPublicKey: $(portfolioPublicKey)
                nginxImage: $(repository):$(tag)
              privateKeyName: $(privateKeyName)
