trigger:
  branches:
    include:
      - master
      - develop

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build container(s)
    jobs:
      - job: Build
        steps:
          - bash: echo "todo"
