trigger:
  branches:
    include:
      - master
      - develop

variables:
  vmImage: 'ubuntu-latest'
  manifests: ./manifests/portfolio/**/*.yaml
  tag: $(Build.BuildId)
  namespace: portfolio
  containerRegistry: docker.io
  imageRepository: survivorbat/portfolio-nginx

stages:
  - stage: BuildPublish
    displayName: Build image(s) and publish them to dockerhub
    jobs:
      - job: BuildPublish
        displayName: Build and Publish
        steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Build services'
            additionalImageTags: $(tag)
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Push services'
            additionalImageTags: $(tag)
  - stage: Deploy
    displayName: Deploy images to kubernetes
    jobs:
      - job: Deploy
        displayName: deploy
        steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'K8s'
              namespace: $(namespace)
              manifests: $(manifests)
              containers:
                $(containerRegistry)/$(imageRepository):$(tag)
