trigger:
  branches:
    include:
      - master
      - develop

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildPublish
    displayName: Build image(s) and publish them to dockerhub
    jobs:
      - job: BuildPublish
        displayName: Build and Publish
        steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Build services'
            includeSourceTags: true
            includeLatestTag: true
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Push services'
            includeSourceTags: true
            includeLatestTag: true
  - stage: Deploy
    displayName: Deploy images to kubernetes
    jobs:
      - job: Deploy
        displayName: deploy
        steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'K8s'
              namespace: 'portfolio'
              manifests: ./manifests/**/*
