trigger:
  branches:
    include:
      - master
      - develop

variables:
  vmImage: 'ubuntu-latest'
  manifests: ./manifests/portfolio/**/*.yaml
  tag: $(Build.BuildId)

stages:
  - stage: BuildPublish
    displayName: Build image(s) and publish them to dockerhub
    jobs:
      - job: BuildPublish
        displayName: Build and Publish
        steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Build services'
            tags: |
              $(tag)
              latest
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Push services'
            tags: |
              $(tag)
              latest
  - stage: Deploy
    displayName: Deploy images to kubernetes
    jobs:
      - job: Deploy
        displayName: deploy
        steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'K8s'
              namespace: 'portfolio'
              manifests: $(manifests)
              tags: $(tag)
