trigger:
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - ./src/frontend/*
      - ./docker/nginx/*

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build container(s)
    jobs:
      - job: Build
        steps:
          - bash: echo "todo"
