trigger:
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - ./src/frontend/*
      - ./docker/*
      - ./deploy-portfolio-pipeline.yaml

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildPublish
    displayName: Build image(s) and publish them to dockerhub
    jobs:
      - job: BuildPublish
        displayName: Build and Publish
        steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Build services'
            includeSourceTags: true
            includeLatestTag: true
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Push services'
            includeSourceTags: true
            includeLatestTag: true
