trigger:
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - ./src/frontend/*
      - ./docker/nginx/*

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build container(s)
    jobs:
      - job: Build
        steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Build services'
            includeSourceTags: true
            includeLatestTag: true
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Push services'
            includeSourceTags: true
            includeLatestTag: true
    