projects:
  host: '%domains.projects%'
  resource: 'routes/projects.yaml'

about:
  host: '%domains.about%'
  resource: 'routes/about.yaml'

contact:
  host: '%domains.contact%'
  resource: 'routes/contact.yaml'

main:
  resource: 'routes/main.yaml'
