common_groups:
  - name: "rungroup"
    gid: "20000"
  - name: "developer"
    gid: "9000"

sudo_groups:
  - developer

common_users:
  - name: "developer"
    group: "developer"
    authorized_key: |
      {{ lookup('env', 'personalPublicKey') }}
      {{ lookup('env', 'portfolioPublicKey') }}
    uid: "9000"
  - name: "runuser"
    group: "rungroup"
    uid: "30000"

default_user: runuser
default_group: rungroup

nginx_image: "{{ lookup('env', 'nginxImage') }}"

pip_install_packages:
  - name: docker
  - name: docker-compose

nginx_fullchain_path: "{{ playbook_dir }}/../terraform/fullchain.pem"
nginx_key_path: "{{ playbook_dir }}/../terraform/key.pem"
