common_groups:
  - name: "rungroup"
    gid: "20000"
  - name: "developer"
    gid: "9000"

sudo_groups:
  - developer

common_users:
  - name: "developer"
    group: "developer"
    authorized_key: |
      {{ lookup('env', 'personal_public_key') }}
      {{ lookup('env', 'portfolio_public_key') }}
    uid: "9000"
  - name: "runuser"
    group: "rungroup"
    uid: "30000"

default_user: runuser
default_group: rungroup

do_token: "{{ lookup('env', 'do_token') }}"
domains: "{{ lookup('env', 'domains').split(',') }}"
