common_groups:
  - name: "rungroup"
    gid: "20000"
  - name: "developer"
    gid: "9000"

sudo_groups:
  - developer

common_users:
  - name: "developer"
    group: "developer"
    authorized_key: |
      {{ lookup('env', 'personalPublicKey') }}
      {{ lookup('env', 'portfolioPublicKey') }}
    uid: "9000"
  - name: "runuser"
    group: "rungroup"
    uid: "30000"

default_user: runuser
default_group: rungroup

nginx_host_letsencrypt_email: "{{ lookup('env', 'letsencryptEmail') }}"
do_token: "{{ lookup('env', 'doToken') }}"

pip_install_packages:
  - name: setuptools
  - name: pyopenssl
    version: 16.2.0
  - name: certbot-dns-digitalocean
  - name: docker
  - name: docker-compose

domains: []
