docker_images:
  - dockerfile: docker/php-fpm/Dockerfile
    path: ../
    name: survivorbat/portfolio-php-fpm
    buildargs:
      USER_ID: 30000
      GROUP_ID: 20000
  - dockerfile: docker/nginx/Dockerfile
    path: ../
    name: survivorbat/portfolio-nginx
  - dockerfile: docker/redis/Dockerfile
    path: ../
    name: survivorbat/redis

docker_tag: latest
add_latest_tag: yes
publish_images: no
docker_username: ""
docker_password: ""
docker_email: ""