---
- hosts: all
  gather_facts: no
  tags: server_install
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python3
      register: output
      changed_when: (output.stdout | length) > 0

    - name: Ensure no python-openssl
      raw: sudo apt remove --auto-remove -y python-openssl
      register: output
      changed_when: (output.stdout | length) > 0

    - name: Ensure pip pyOpenSSL
      raw: pip3 install pyOpenSSL
      register: output
      changed_when: (output.stdout | length) > 0

- name: Ensure common roles
  hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - common

- name: Ensure portfolio
  hosts: portfolio
  roles:
    - portfolio
