---
- hosts: all
  gather_facts: no
  tags: server_install
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python3
      register: output
      changed_when: (output.stdout | length) > 0

- name: Ensure common roles
  hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - common

- name: Ensure portfolio
  hosts: portfolio
  roles:
    - portfolio

- name: Ensure margo
  hosts: margo
  vars:
    server_folder: /home/developer/minecraft
    environment:
      JVM_DD_OPTS=fml: queryResult:confirm
      MC_MAXMEM: 1500m
  roles:
    - minecraft_server
