apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: portfolio-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-svc
    spec:
      containers:
        - name: portfolio-svc
          image: survivorbat/portfolio-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 20Mi
