version: '3.5'

networks:
  nginx: ~

volumes:
  db-data: ~

services:
  nginx:
    image: survivorbat/portfolio-nginx:latest
    restart: always
    ports:
      - 80:8080
      - 443:8443
    networks:
      - nginx
