version: '3.5'

networks:
  nginx: ~
  cache: ~
  mysql: ~

volumes:
  db-data: ~
  log: ~

services:
  php-fpm:
    image: survivorbat/portfolio-php-fpm:latest
    restart: always
    expose:
      - 9000
    networks:
      - nginx
      - cache
      - mysql
    environment:
      DATABASE_HOSTNAME: mysql
      DATABASE_NAME: portfolio
      DATABASE_USER: portfolio
      REDIS_HOST: redis
      REDIS_PORT: 6379

  nginx:
    image: survivorbat/portfolio-nginx:latest
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - log:/var/log/nginx
    networks:
      - nginx

  redis:
    image: survivorbat/redis:latest
    restart: always
    networks:
      - cache
    expose:
      - 6379

  mysql:
    image: mysql:5.7
    networks:
      - mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio
