version: '3.5'

services:
  nginx:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/maarten.dev/nginx:/etc/nginx/temp
    environment:
      - server_name=${server_name}
      - hsts_max_time=30000000
      - cache_max_time=60m
  node:
    image: survivorbat/portfolio-node:${docker_tag}
