version: '3.5'

volumes:
  development_ssl: ~

services:
  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      cache_max_time: 1
    volumes:
      - ./nginx/etc/nginx/temp:/etc/nginx/temp:cached
