version: '3.5'

services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      cache_max_time: 1
    restart: always
    ports:
      - 80:8080
      - 443:8443
