version: '3.5'

volumes:
  uploads: ~
  bundles: ~

services:
  nginx:
    image: survivorbat/portfolio-nginx:${docker_tag}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      server_name: ${server_name}
      hsts_max_time: 30000000
      cache_max_time: 36000000
