framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection: true

    session:
        handler_id: app.session.handler
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']

    http_method_override: true
