security:
    providers:
        in_memory:
            memory:
                users:
                    maartendev:
                        password: '%env(ADMIN_PASSWORD)%'
                        roles: 'ROLE_SUPER_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))
            security: false

        admin:
            pattern: ^/UqUMbUkG
            http_basic: ~

        main:
            pattern: ^/
            security: false

    access_control:
        - { path: ^/UqUMbUkG, role: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
