---
- name: "Ensure {{ project_dir }}"
  file:
    state: directory
    path: "{{ project_dir }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0755

- name: "Ensure files in {{ project_dir }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0755
  with_items: "{{ project_dir_files }}"

- name: "Ensure static files in {{ nginx_static_dir }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0755
  with_items: "{{ nginx_static_files }}"

- name: "Restart"
