admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /UqUMbUkG

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /UqUMbUkG

main:
  prefix: /
  resource: 'config/routes.yaml'
