trigger:
  branches:
    include:
      - master
      - develop

variables:
  vmImage: 'ubuntu-latest'

  playbook: src/frontend/ansible/deploy.yaml
  host: maarten.dev

  containerRegistry: docker.io
  imageRepository: survivorbat/portfolio-nginx
  dockerComposePath: src/docker-compose.yml
  tag: $(Build.BuildId)

stages:
  - stage: BuildPublish
    displayName: Build image(s) and publish them to dockerhub
    jobs:
      - job: BuildPublish
        displayName: Build and Publish
        steps:
        - task: DockerCompose@0
          inputs:
            dockerComposeFile: $(dockerComposePath)
            action: 'Build services'
            additionalImageTags: $(tag)
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: $(dockerComposePath)
            action: 'Push services'
            additionalImageTags: $(tag)
  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - bash: pip install ansible
            displayName: Pip install ansible
          - bash: ansible-playbook -i $(host), $(playbook)
            displayName: Run ansible playbook
