default_user: root
default_group: root

nginx_image: "nginx:latest"
nginx_name: "nginx_portfolio"
nginx_environment:
  hostname: "{{ inventory_hostname }}"
  hsts_max_time: "3600000000"
  cache_max_time: "7d"

domains: []
