---
- name: "Build images with tag {{ docker_tag }}"
  docker_image:
    source: build
    build:
      path: "{{ item.path }}"
      dockerfile: "{{ item.dockerfile }}"
      pull: no
      args: "{{ item.buildargs | default(omit) }}"
      cache_from:
        - "{{ item.name }}:latest"
    name: "{{ item.name }}"
    tag: "{{ docker_tag }}"
  loop: "{{ docker_images }}"
  tags: build_images

- name: "Add latest tag to built images"
  docker_image:
    source: pull
    name: "{{ item.name }}:{{ docker_tag }}"
    repository: "{{ item.name }}:latest"
    build:
      pull: no
  loop: "{{ docker_images }}"
  when: add_latest_tag | bool
  tags: build_images
