trigger:
  branches:
    include:
      - master

variables:
  vmImage: 'ubuntu-latest'
  terraformDirectory: 'common/terraform/digitalocean'

stages:
  - stage: Deploy
    displayName: Setup infrastructure with Terraform
    jobs:
      - job: Setup
        displayName: Setup infrastructure with Terraform
        steps: 
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              workingDirectory: $(terraformDirectory)
          - task: TerraformCLI@0
            inputs:
              command: 'validate'
              workingDirectory: $(terraformDirectory)
          - task: TerraformCLI@0
            inputs:
              command: 'apply'
              workingDirectory: $(terraformDirectory)

      - job: Deploy
        dependsOn: Setup
        steps: []
