---
- hosts: all
  gather_facts: no
  tags: server_install
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python
      register: output
      changed_when: (output.stdout | length) > 0

- name: Ensure common roles
  hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.certbot
    - geerlingguy.pip
    - common

- name: Ensure portfolio
  hosts: all
  roles:
    - portfolio
