version: '3.5'

volumes:
  ssl-dev: ~

services:
  nginx:
    build:
      context: frontend
    environment:
      hostname: localhost
      cache_max_time: "0"
      hsts_max_time: "1"
      env: "dev"
    restart: always
    volumes:
      - ssl-dev:/etc/letsencrypt/live/localhost:delegated
      - ./frontend/nginx/etc/nginx/temp/nginx.conf:/etc/nginx/temp/nginx.conf
      - ./frontend/nginx/etc/nginx/temp/conf.d:/etc/nginx/temp/conf.d
    ports:
      - 80:8080
      - 443:8443

  node:
    image: "node:13.7.0-alpine"
    working_dir: /app
    restart: always
    expose:
      - 3000
    volumes:
      - ./frontend:/app
    command: ["/bin/sh", "-c", "npm install && npm start"]

  ssl-dev:
    build:
      context: ssl-dev
    volumes:
      - ssl-dev:/ssl
