App\Entity\ContactOption:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    label:
      type: string
      options:
        default: ''
    value:
      type: string
      options:
        default: ''
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
