App\Entity\ExperienceTopic:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    since:
      type: datetime
    explanation:
      type: text
      options:
        default: ''
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update

  manyToOne:
    technology:
      targetEntity: App\Entity\Technology
      mappedBy: experienceTopics
      inversedBy: experienceTopics
