App\Entity\Image:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    mimeType:
      type: string
      options:
        default: ''
    filename:
      type: string
      options:
        default: ''
    filePath:
      type: string
      options:
        default: ''
    imageUpdated:
      type: datetime
      nullable: true
    publicPath:
      type: string
      options:
        default: ''
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update

  manyToOne:
    project:
      targetEntity: App\Entity\Project
      mappedBy: images
      inversedBy: images

  oneToMany:
    technology:
      targetEntity: App\Entity\Technology
      mappedBy: image
      inversedBy: image
    statusUpdate:
      targetEntity: App\Entity\StatusUpdate
      mappedBy: image
      inversedBy: image
