App\Entity\Technology:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    name:
      type: string
      options:
        default: ''
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update

  oneToMany:
    experienceTopics:
      targetEntity: App\Entity\ExperienceTopic
      mappedBy: technology
      inversedBy: technology
      cascade: [persist, remove]

  manyToOne:
    image:
      targetEntity: App\Entity\Image
      mappedBy: technology
      inversedBy: technology
      cascade: [persist, remove]

  manyToMany:
    statusUpdates:
      targetEntity: App\Entity\StatusUpdate
      inversedBy: technologies
      joinColumns:
        technology_id:
          referencedColumnName: id
      inverseJoinColumns:
        status_update_id:
          referencedColumnName: id
    projects:
      targetEntity: App\Entity\Project
      inversedBy: technologies
      joinColumns:
        technology_id:
          referencedColumnName: id
      inverseJoinColumns:
        project_id:
          referencedColumnName: id
