apiVersion : apps/v1
kind: Deployment
metadata:
  name: portfolio-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-nginx
  template:
    metadata:
      labels:
        app: portfolio-nginx
    spec:
      containers:
        - name: portfolio-nginx
          image: survivorbat/portfolio-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 20Mi
          env:
            - name: cache_max_time
              value: "10000000000"
